spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veyradb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: VeyraInventorySecretKey2026ThisMustBeAtLeast256BitsLongForHS256Algorithm!
  expiration: 86400000   # 24 hours in ms

cors:
  allowed-origin: http://localhost:4200
